site_name: Лабораторные работы по Web-программированию
nav:
  - Главная: index.md
  - Лабораторная работа №1: report_1.md
  - Лабораторная работа №2: report_2.md
  - Практическая работа 3.1: practice_3_1.md
  - Практическая работа 3.2: practice_3_2.md
  - Лабораторная работа №3: report_3.md
  - Лабораторная работа №4: report_4.md


theme:
  name: material
  language: ru
