site_name: Лабораторные работы по Web-программированию
nav:
  - Главная: index.md
  - Лабораторная работа №1: report_1.md
  - Лабораторная работа №2: report_2.md


theme:
  name: material
  language: ru
